scenicarea/apps/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('<int:id>/', views.new_conversation, name='new'),
]

scenicarea/apps/merchant/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from apps.merchant import views
from .forms import LoginForm

urlpatterns = [
    path('', views.index, name='index'),
    path('good/<int:id>/change/', views.details, name='details'),
    path('good/create/', views.create_good, name='create_good'),
    path('good/<int:id>/delete/', views.delete_good, name='delete_good'),
    path('good/search/', views.search_good, name='search_good'),
    path('conversation/', views.merchant_conversation, name='conversation'),
    path('message/<int:id>/send', views.merchant_message, name='message_send'),
    path('singup/', views.sing_up, name='sing_up'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='merchant/log_in.html'), name='log_in'),
    path('logout/', auth_views.LogoutView.as_view(template_name='merchant/log_in.html'), name='log_out'),
]
app_name = 'merchant'

scenicarea/scenicarea/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.api.urls')),
    path('merchant/', include('apps.merchant.urls')),
    path('inbox/', include('apps.conversation.urls')),
    path('wallet/', include('apps.wallet.urls'),)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scenicarea/apps/conversation/models.py
from django.db import models
from django.contrib.auth.models import User


from apps.merchant.models import Commodity


# Create your models here.
class Conversation(models.Model):
    commodity = models.ForeignKey(Commodity, related_name='conversations', on_delete=models.CASCADE, verbose_name='商品')
    members = models.ManyToManyField(User, related_name='conversations', verbose_name='用户')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_date = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        ordering = ('-update_date',)

class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE, verbose_name='对话')
    content = models.TextField(verbose_name='消息')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE, verbose_name='发起用户')

scenicarea/apps/merchant/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import date, datetime

# Create your models here.
class Commodity(models.Model):
    title = models.CharField(verbose_name='标题', max_length=200)
    details = models.TextField(verbose_name='商品详情', max_length=2000)
    price = models.DecimalField(verbose_name='商品价格', max_digits=5, decimal_places=2)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, blank=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True, blank=True)
    inventory = models.PositiveIntegerField(verbose_name='商品库存', blank=True, default=0)
    picture = models.ImageField(verbose_name='商品主图', upload_to='images/')
    user = models.ForeignKey(User, related_name='commodity', on_delete=models.CASCADE, default=1)


    def __str__(self) -> str:
        return self.title
    
class AssistantImages(models.Model):
    picture = models.ImageField(verbose_name='商品主图', upload_to='images/', null=True, blank=True, default=None)
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, blank=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True, blank=True)

scenicarea/apps/conversation/forms.py
from django import forms

from .models import ConversationMessage


TEXTINPUTCLASS = 'form-control'

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'class': TEXTINPUTCLASS, 'rows':1}),
        }

scenicarea/apps/merchant/forms.py
from django import forms
from django.forms import inlineformset_factory, modelformset_factory
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User

from .models import Commodity, AssistantImages

TEXTINPUTCLASS = 'form-control'

class ToppingSelect(forms.Select):
    def create_option(self, name, value, label, selected, index, subindex=None, attrs=None):
        option = super().create_option(name, value, label, selected, index, subindex, attrs)
        if value:
            option["attrs"]["data-title"] = value.instance.title
        return option


class GoodAddForm(forms.ModelForm):
    template_name = "merchant/create.html"
    class Meta:
        model = Commodity
        # fields = ['title']
        fields = '__all__'
        exclude = ['create_date', 'update_date', 'user']
        widgets = {
            'title': forms.TextInput(attrs={'class': TEXTINPUTCLASS}),
            'details': forms.Textarea(attrs={'class': TEXTINPUTCLASS, 'rows': 6}),
            'price': forms.NumberInput(attrs={'class': TEXTINPUTCLASS}),
            'inventory': forms.NumberInput(attrs={'class': TEXTINPUTCLASS}),
            'picture': forms.FileInput(attrs={'class': TEXTINPUTCLASS}),
        }

    def clean_title(self, *args, **kwargs):
        title = self.cleaned_data.get('title')
        if 'CFE' in title:
            raise forms.ValidationError('包含了CFE关键字')
        return title
    
class AssistantImagesForm(forms.ModelForm):
    class Meta:
        model = AssistantImages
        fields = '__all__'
        exclude = ['create_date', 'update_date', 'commodity']
        widgets = {
            'picture': forms.FileInput(attrs={'class': TEXTINPUTCLASS}),
            # 'commodity': forms.Select(attrs={'class': 'form-select'}),
        }

AsInlineFormSet = modelformset_factory(AssistantImages, form=AssistantImagesForm, extra=2)
    
class GoodChangeForm(GoodAddForm):
    template_name = "merchant/details.html"
        
class SingupForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': TEXTINPUTCLASS}),
            'email': forms.EmailInput(attrs={'class': TEXTINPUTCLASS}),
            'password1': forms.PasswordInput(attrs={'class': TEXTINPUTCLASS}),
            'password2': forms.PasswordInput(attrs={'class': TEXTINPUTCLASS}),
        }

class LoginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(attrs={'class': TEXTINPUTCLASS}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': TEXTINPUTCLASS}))

scenicarea/apps/conversation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Conversation
from .forms import ConversationMessageForm

from apps.merchant.models import Commodity

# Create your views here.
@login_required(login_url='/login/')
def new_conversation(request, id):
    # 获取要对话的商品
    obj_commodity = get_object_or_404(Commodity, id=id)
   
    if obj_commodity.user == request.user:
        # 如果创建对话的用户是这个商品的创建者
        # 自动定向到这个创建者的商品列表
        return redirect(reverse('merchant:index'))
    
    # 查找对话表中是否存在和这个商品相关的对话
    # 在过滤相关对话记录中关于创建对话用户的所有对话
    obj_conversation = Conversation.objects.filter(commodity=obj_commodity).filter(members__in=[request.user.id]).first()

    if obj_conversation:
        qs_message = obj_conversation.messages.all()
    else:
        qs_message = []

    if request.method == 'POST':
        # 把发送的信息放到form中验证
        form = ConversationMessageForm(request.POST)
        if form.is_valid():
            # 如果验证通过
            # 创建一条关于这个商品的对话
            # 保存创建对话的用户id和关于这个商品的创建者id
            if not obj_conversation:
                obj_conversation = Conversation.objects.create(commodity=obj_commodity)
                obj_conversation.members.add(request.user)
                obj_conversation.members.add(obj_commodity.user)
                obj_conversation.save()

            # 把发送的信息保存到信息表
            # 在将这条对话的id和创建对话的用户id保存到信息表
            form_conversation_message = form.save(commit=False)
            form_conversation_message.conversation = obj_conversation
            form_conversation_message.created_by = request.user
            form_conversation_message.save()

            # 保存完成重定向到对话页面
            return redirect(reverse('conversation:new', kwargs={'id': id}))
        
    else:
        form = ConversationMessageForm()
    
    context = {
        'form': form,
        'id': id,
        'queryset': qs_message,
    }
    return render(request, 'conversation/new.html', context)

scenicarea/apps/merchant/views.py
from django.shortcuts import render, redirect, HttpResponse, get_object_or_404
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from django.db.models import F, Count, OuterRef, Subquery


from .models import Commodity, AssistantImages
from .forms import GoodAddForm, AssistantImagesForm, AsInlineFormSet, SingupForm

from apps.conversation.models import Conversation, ConversationMessage
from apps.conversation.forms import ConversationMessageForm

# Create your views here.
@login_required
def index(request):
    queryset = Commodity.objects.filter(user=request.user)
    context = {
        'queryset': queryset,
        'paginator': queryset.count()
    }
    return render(request, 'merchant/index.html', context)

@login_required
def details(request, id):
    obj_good = get_object_or_404(Commodity, id=id, user=request.user)
    # obj_as_image = get_object_or_404(AssistantImages, id=id)

    good_form = GoodAddForm(request.POST or None, request.FILES or None, instance=obj_good)
    # as_image_form = AssistantImagesForm(request.POST or None, request.FILES or None, instance=obj_as_image)

    if request.method == 'POST':
        if good_form.is_valid():
            good_form.save()
            return redirect(reverse('merchant:index'))
        
    context = {
        'good_form': good_form,
        # 'as_image_form': as_image_form,
        'id': id
    }
    return render(request, 'merchant/details.html', context)

@login_required
def delete_good(request, id): 
    obj = get_object_or_404(Commodity, id=id, user=request.user)  
    if request.method == 'POST':
        obj.delete()
        return redirect(reverse('merchant:index'))
    context = {
        'obj': obj,
        'referer': request.headers['Referer']
    }
    return render(request, 'merchant/delete.html', context)

@login_required
def create_good(request): 
    if request.method == 'POST':
        good_form = GoodAddForm(request.POST, request.FILES)
        as_image_form = AssistantImagesForm(request.POST, request.FILES)
        if good_form.is_valid() and as_image_form.is_valid():
            obj_good = good_form.save(commit=False)
            obj_good.user = request.user
            obj_as_image = as_image_form.save(commit=False)
            obj_as_image.commodity = obj_good
            obj_good.save()
            obj_as_image.save()
            return redirect(reverse('merchant:index'))
    else:
        good_form = GoodAddForm()
        as_image_form = AssistantImagesForm()
    context = {
        'good_form': good_form,
        'as_image_form': as_image_form,
    }
    return render(request, 'merchant/create.html', context)

def sing_up(request):
    if request.method == "POST":
        print(request.POST)
        form = SingupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('merchant:log_in'))
    else:
        form = SingupForm()
    context = {
        'form': form
    }
    return render(request, 'merchant/sing_up.html', context)

@login_required
def search_good(request):
    query = request.GET.get('query')
    if query:
        queryset = Commodity.objects.filter(user=request.user, title__icontains=query)
    else:
        queryset = Commodity.objects.filter(user=request.user)
    context = {
        'query': query,
        'queryset': queryset,
        'paginator': queryset.count()
    }
    return render(request, 'merchant/index.html', context)

@login_required
def merchant_conversation(request):
    subquery1 = ConversationMessage.objects.filter(
        conversation=OuterRef('pk')
    ).order_by('-create_date').values('content')[:1]

    subquery2 = Conversation.objects.filter(
        commodity=OuterRef('commodity')
    ).values('commodity__title')[:1]

    conversations = Conversation.objects.annotate(
        latest_message_content=Subquery(subquery1),
        latest_message_sender=Subquery(subquery1.values('created_by__username')),
        latest_message_timestamp=Subquery(subquery1.values('create_date')),
        latest_commodity_title = Subquery(subquery2.values('commodity__title')),
        latest_commodity_picture = Subquery(subquery2.values('commodity__picture')),
    ).filter(members__id__in=[request.user.id])

    # print(conversations)
    # print(conversations.query)
    context = {
        'queryset': conversations,
        # 'paginator': qs_com.count()
    }
    return render(request, 'merchant/conversation.html', context)
    # return HttpResponse('ok')


@login_required
def merchant_message(request, id):
    qs_messages = ConversationMessage.objects.select_related('conversation', 'created_by').filter(
        conversation__id__in=[id]
    ).values(
        'created_by',
        'created_by__username',
        'content',
        'create_date',
    )
    obj = get_object_or_404(Conversation, id=id)
    if request.method == 'POST':
        form = ConversationMessageForm(request.POST)
        if form.is_valid():
            form_conversation_message = form.save(commit=False)
            form_conversation_message.conversation = obj
            form_conversation_message.created_by = request.user
            form_conversation_message.save()

            return redirect(reverse('merchant:message_send', kwargs={'id': id}))

    form = ConversationMessageForm()
    context = {
        'queryset': qs_messages,
        'form': form,
        'id': id,
    }
    return render(request, 'merchant/message_inbox.html', context)

scenicarea/apps/merchant/templates/merchant/base.html
{% load static %}

<!doctype html>
<html lang="en-US">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>
  <body>
    <div class="container-fluid" id="container">
        <div id="header" class="row align-items-center py-3" style="background-color: #417690;">
            {% block header %}
            <div class="col-md-3" style="color: #F5DD5D;">
                <h3 class="mb-0">商家管理中心</h3>
            </div>

            {% if request.user.is_authenticated %}
                <div class="col-md-auto ms-md-auto">
                    <p class="mb-0" style="color: #ffffff;">你好: {{request.user}}</p>
                </div>
                <div class="col-md-auto">
                    <a href="{% url 'merchant:conversation' %}" class="btn" style="background: #F5DD5D;">对话</a>
                </div>
                <div class="col-md-auto">
                    <a href="{% url 'merchant:log_out' %}" class="btn" style="background: #F5DD5D;">退出</a>
                </div>
            {% else %}
                <div class="col-md-auto ms-md-auto">
                    <a href="{% url 'merchant:sing_up' %}" class="btn" style="background: #F5DD5D;">注册</a>
                </div>
                <div class="col-md-auto">
                    <a href="{% url 'merchant:log_in' %}" class="btn" style="background: #F5DD5D;">登录</a>
                </div>
            {% endif %}
            {% endblock %}
        </div>
        <div id="main">
            {% block main %}{% endblock %}
        </div>
        <div id="footer">
            {% block footer %}{% endblock %}
        </div>
    </div>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-ep+dxp/oz2RKF89ALMPGc7Z89QFa32C8Uv1A3TcEK8sMzXVysblLA3+eJWTzPJzT" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/mhDoLbDldZc3qpsJHpLogda//BVZbgYuw6kof4u2FrCedxOtgRZDTHgHUhOCVim" crossorigin="anonymous"></script>
  </body>
</html>

scenicarea/apps/merchant/templates/merchant/conversation.html
{% extends 'merchant/index.html' %}

{% load static %}

{% block title%}对话{% endblock %}

{% block context %}
<div class="row py-3">
    <div class="col-md-12">
        <h3 class="mb-0">所有对话</h3>
    </div>
</div>

<div class="row">
    <table class="table table-bordered table-hover">
        <thead>
            <tr class="text-center">
                <th class="col-md-1">
                    主图
                </th>
                <th class="col-md-2">
                    商品标题
                </th>
                <th class="col-md-1">
                    来自用户
                </th>
                <th class="col-md-4">
                    消息内容
                </th>
                <th class="col-md-2">
                    发送时间
                </th>
                <th class="col-md-2">
                    操作
                </th>
            </tr>
        </thead>
        <tbody>
            {% for item in queryset %}
                <tr class="align-middle text-center">
                    <td>
                        <img src="/media/{{item.latest_commodity_picture}}" alt="主图" width="100%">
                    </td>
                    <td>
                        {{item.latest_commodity_title}}
                    </td>
                    <td>
                        {{item.latest_message_sender}}
                    </td>
                    <td>
                        <p class="text-break mb-0">{{item.latest_message_content}}</p>
                    </td>
                    <td>
                        {{item.latest_message_timestamp}}
                    </td>
                    <td>
                        <a href="{% url 'merchant:message_send' item.id %}" class="btn btn-primary">
                            回复
                        </a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    <div class="col-md-auto">
        <P>总数：{{paginator}}</P>
    </div>

</div>
{% endblock %}

scenicarea/apps/merchant/templates/merchant/create.html
{% extends 'merchant/index.html' %}

{% load static %}

{% block title%}增加商品{% endblock %}

{% block context %}
    <div class="row py-3">
        <div class="col-md">
            <h3>{% block panel %}增加商品{% endblock %}</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
        </div>
    </div>

    <div class="row">
        <div class="col-md-6">     
            <form enctype="multipart/form-data" method="post" action="{% block action %}{% url 'merchant:create_good' %}{% endblock %}" class="py-3">
                {% csrf_token %}
                {% for field in good_form %}
                    <div class="row mb-3">
                        <div class="col-md-2 align-self-center">
                            <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                        </div>
                        <div class="col-md-10">
                            {{ field }}
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-auto offset-2">
                            <strong style="color: rgb(229, 11, 11);">{{ field.errors }}</strong>
                        </div>
                    </div>
                {% endfor %}
                {% for field in as_image_form %}
                <div class="row mb-3">
                    <div class="col-md-2 align-self-center">
                        <label for="{{ field.id_for_label }}">{{ field.label }}:</label>
                    </div>
                    <div class="col-md-10">
                        {{ field }}
                    </div>
                </div>
                <div class="row">
                    <div class="col-auto offset-2">
                        <strong style="color: rgb(229, 11, 11);">{{ field.errors }}</strong>
                    </div>
                </div>
                {% endfor %}
            
                <div class="row">
                    <div class="col-md-12">
                        <hr>
                    </div>
                </div>
            
                <div class="mt-3 row align-items-center">
                    <div class="col-auto">
                        <input type="submit" value="保存" name="save" class="btn btn-info text-light">
                    </div>
                    {% block delete_button %}
            
                    {% endblock %}
                </div>
            </form>
        </div>
        <div class="col-md-6">
            {% block goodimage %}
            
            {% endblock %}
        </div>
    </div>
{% endblock %}

scenicarea/apps/merchant/templates/merchant/delete.html
{% extends 'merchant/index.html' %}

{% load static %}

{% block context %}
    <div class="row py-3">
        <div class="col-md-auto">
            <h3>正在删除商品</h3>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <hr>
        </div>
    </div>
    <div class="row mb-3">
        <form enctype="application/x-www-form-urlencoded" method="post" action="{% url 'merchant:delete_good' obj.id %}" class="py-3">
    {% csrf_token %}


    <div class="row mb-3">
        <div class="col-md-auto">
            <p>你确认想要删除 标题是：{{obj.title}} 的商品和他下面所有相关的项目？</p>
        </div>
    </div>

    <div class="mb-3 row row-cols-2 align-items-center">
        <div class="col-auto">
            <input type="submit" value="确定" name="confirmed" class="py-2 btn btn-danger text-light">
        </div>
        <div class="col-auto">
            <a href="{{referer}}" class="py-2 btn btn-info text-light">返回</a>
        </div>
    </div>

        </form>
    </div>
{% endblock %}

scenicarea/apps/merchant/templates/merchant/details.html
{% extends 'merchant/create.html' %}

{% load static %}

{% block title%}商品详情{% endblock %}

{% block panel %}修改商品{% endblock %}

{% block action %}
{% url 'merchant:details' id %}
{% endblock %}

{% block delete_button %}
<div class="col-md-auto">
    <a href="{% url 'merchant:delete_good' id %}" class="btn btn-danger link-light">删除</a>
</div>
{% endblock %}

{% block goodimage %}
<div class="row mb-3">
    <div class="col-md-12">
        <h5 class="mb-0">主图预览:</h5>
    </div>
</div>
<div class="row">
    <div class="col-md-12">
        <img src="/media/{{good_form.picture.value}}" alt="" class="img-fluid">
    </div>
</div>
{% endblock %}

scenicarea/apps/merchant/templates/merchant/index.html
{% extends 'merchant/base.html' %}

{% load static %}

{% block title%}商家站点管理{% endblock %}


{% block main %}
<div class="row">
    <div class="col-md-2">
        <div class="row">
            <div class="col-md-12">
                <div class="list-group list-group-flush">
                    <a href="{% url 'merchant:index' %}" class="list-group-item">首页</a>
                    <a href="#" class="list-group-item">A second link item</a>
                    <a href="#" class="list-group-item">A third link item</a>
                    <a href="#" class="list-group-item">A fourth link item</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col-md-10">
        {% block context %}
        <div class="row py-3">
            <div class="col-md-auto">
                <h3 class="mb-0">商品列表</h3>
            </div>
            <div class="col-md-auto align-self-center ms-md-auto">
                <a href="{% url 'merchant:create_good' %}" class="btn btn-primary">增加商品</a>
            </div>
        </div>
        <div class="row py-3">
            <div class="col-md-12">
                <form action="{% url 'merchant:search_good' %}" method="get">
                    <div class="row">
                        <div class="col-md align-self-center">
                            <input type="text" name="query" id="query" class="form-control" value="{{query}}" placeholder="输入商品标题">
                        </div>
                        <div class="col-md">
                            <button class="btn btn-primary" type="submit">搜索</button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
        <div class="row">
            <table class="table table-bordered table-hover">
                <thead>
                    <tr class="text-center">
                        <th>ID</th>
                        <th>主图</th>
                        <th>
                            标题
                        </th>
                        <th>
                            价格
                        </th>
                        <th>
                            创建时间
                        </th>
                        <th>
                            操作
                        </th>
                    </tr>
                </thead>
                <tbody>
                    {% for item in queryset %}
                        <tr class="align-middle text-center">
                            <th>{{item.id}}</th>
                            <td class="col-md-1">
                                <img src="/media/{{item.picture}}" alt="主图" width="100%">
                            </td>
                            <td>
                                <a style="outline: none; text-decoration: none;" href="{% url 'merchant:details' item.id %}" class="link-dark" >
                                {{item.title}}
                                </a>
                            </td>
                            <td>
                                {{item.price}}
                            </td>
                            <td>
                                {{item.create_date}}
                            </td>
                            <td>
                                <a href="{% url 'merchant:details' item.id %}" class="btn btn-primary">
                                    编辑
                                </a>
                                <a href="{% url 'merchant:delete_good' item.id %}" class="btn btn-danger">
                                    删除
                                </a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
            <div class="col-md-auto">
                <P>总数：{{paginator}}</P>
            </div>
        
        </div>
        {% endblock %}
    </div>
    
</div>
{% endblock %}

scenicarea/apps/merchant/templates/merchant/log_in.html
{% extends 'merchant/base.html' %}

{% load static %}

{% block title%}登录{% endblock %}

{% block main %}
<div class="row mb-3">
    <div class="col-md-4 offset-md-4 mt-4" style="background-color: rgb(238, 238, 238);">
        <h4 class="my-4 text-center">
            登录
        </h4>
        <hr class="border border-dark border-1 opacity-50">
        <form action="{% url 'merchant:log_in' %}" method="post" >
            {% csrf_token %}
            <div class="row mb-3">
                <label for="#" class="form-label">用户名:</label>
                <div class="col-md-12">
                    {{ form.username }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="#" class="form-label">密码:</label>
                <div class="col-md-12">
                    <input type="password" class="form-control" name="password" id="id_password1" required>
                </div>
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="row mb-3">
                <div class="col-auto">
                    {% for field in form %}
                    {{ field.errors}}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            </div>
            {% endif %}
            
            <div class="row mb-4">
                <div class="col-md-3" style="margin-left: 5rem;">
                    <button type="submit" class="btn btn-primary" style="width: 16rem;">登录</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}

scenicarea/apps/merchant/templates/merchant/sing_up.html
{% extends 'merchant/base.html' %}

{% load static %}

{% block title%}注册{% endblock %}

{% block main %}
<div class="row mb-3">
    <div class="col-md-4 offset-md-4 mt-4" style="background-color: rgb(238, 238, 238);">
        <h4 class="my-4 text-center">
            注册
        </h4>
        <hr class="border border-dark border-1 opacity-50">
        <form action="{% url 'merchant:sing_up' %}" method="post" >
            {% csrf_token %}
            <div class="row mb-3">
                <label for="#" class="form-label">用户名:</label>
                <div class="col-md-12">
                    {{ form.username }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="#" class="form-label">邮箱:</label>
                <div class="col-md-12">
                    {{ form.email }}
                </div>
            </div>
            <div class="row mb-3">
                <label for="#" class="form-label">密码:</label>
                <div class="col-md-12">
                    <input type="password" class="form-control" name="password1" id="id_password1" required>
                </div>
            </div>
            <div class="row mb-3">
                <label for="#" class="form-label">确认密码:</label>
                <div class="col-md-12">
                    <input type="password" class="form-control" name="password2" id="id_password2" required>
                </div>               
            </div>

            {% if form.errors or form.non_field_errors %}
            <div class="row mb-3">
                <div class="col-auto">
                    {% for field in form %}
                    {{ field.errors}}
                    {% endfor %}

                    {{ form.non_field_errors }}
                </div>
            </div>
            {% endif %}
            
            <div class="row mb-4">
                <div class="col-md-3" style="margin-left: 5rem;">
                    <button type="submit" class="btn btn-primary" style="width: 16rem;">提交</button>
                </div>
            </div>
        </form>
    </div>
</div>
{% endblock %}