scenicarea/apps/api/urls.py
from django.urls import path, reverse
from django.contrib.auth import views as auth_views

from apps.api import views

from apps.merchant.forms import LoginForm

urlpatterns = [
    path('', views.index, name='index'),
    path('good/<int:id>/', views.details, name='details'),
    path('singup/', views.sing_up, name='sing_up'),
    path('center/', views.center, name='center'),
    path('conversation/index/', views.conversation, name='conversation'),
    path('friend/index/', views.friend_list, name='friend_list'),
    path('friend/search/', views.search_friend, name='search_friend'),
    path('friend/<int:id>/delete/', views.delete_friend, name='delete_friend'),
    path('gift/', views.gift_index, name='gift_index'),
    path('gift/receive/index/', views.gift_receive_index, name='gift_receive_index'),
    path('gift/<int:id>/details/', views.gift_details, name='gift_details'),
    path('gift/<int:id>/receive/', views.gift_receive, name='gift_receive'),
    path('gift/<int:gift_id>/<int:good_id>/forward/', views.forward_gift, name='forward_gift'),
    path('gift/<int:id>/new/', views.new_gift, name='new_gift'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='api/log_in.html', next_page='/'), name='log_in'),
    path('logout/', auth_views.LogoutView.as_view(template_name='api/log_in.html', next_page='/login/'), name='log_out'),
]
app_name = 'api'

scenicarea/apps/conversation/urls.py
from django.urls import path

from . import views

app_name = 'conversation'

urlpatterns = [
    path('<int:id>/', views.new_conversation, name='new'),
]

scenicarea/apps/merchant/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views

from apps.merchant import views
from .forms import LoginForm

urlpatterns = [
    path('', views.index, name='index'),
    path('good/<int:id>/change/', views.details, name='details'),
    path('good/create/', views.create_good, name='create_good'),
    path('good/<int:id>/delete/', views.delete_good, name='delete_good'),
    path('good/search/', views.search_good, name='search_good'),
    path('conversation/', views.merchant_conversation, name='conversation'),
    path('message/<int:id>/send', views.merchant_message, name='message_send'),
    path('singup/', views.sing_up, name='sing_up'),
    path('login/', auth_views.LoginView.as_view(authentication_form=LoginForm, template_name='merchant/log_in.html'), name='log_in'),
    path('logout/', auth_views.LogoutView.as_view(template_name='merchant/log_in.html'), name='log_out'),
]
app_name = 'merchant'

scenicarea/apps/wallet/urls.py
from django.urls import path, reverse

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/recharge/', views.recharge, name='recharge'),
]
app_name = 'wallet'

scenicarea/scenicarea/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.api.urls')),
    path('merchant/', include('apps.merchant.urls')),
    path('inbox/', include('apps.conversation.urls')),
    path('wallet/', include('apps.wallet.urls'),)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scenicarea/apps/api/models.py
from django.db import models
from django.contrib.auth.models import User

from apps.merchant.models import Commodity

# Create your models here.
class Nexus(models.Model):
    name = models.CharField(verbose_name='关系名称', unique=True, max_length=10)
    members = models.ManyToManyField(User, verbose_name='与谁建立关系', through='Concern', through_fields=('nexus', 'created_by'))
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)

class Concern(models.Model):
    nexus = models.ForeignKey(Nexus, on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    passive_by = models.ForeignKey(User, on_delete=models.CASCADE, related_name='passive_by')
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True)

class GiftStatus(models.Model):
    name = models.CharField(verbose_name='礼物状态', unique=True, max_length=10)

class Gift(models.Model):
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE, related_name='commodity_gift')
    relationship = models.ManyToManyField(User, through='GiftRelationship', through_fields=('gift', 'gift_user', 'receive_user'))

class GiftRelationship(models.Model):
    gift = models.ForeignKey(Gift, on_delete=models.CASCADE)
    address = models.CharField(verbose_name='接收地址', max_length=100, default=None)
    status = models.ForeignKey(GiftStatus, on_delete=models.CASCADE, related_name='giftstatus', default=None)
    gift_user = models.ForeignKey(User, on_delete=models.CASCADE)
    receive_user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='receive_user')
    forward = models.BooleanField(verbose_name='是否转增', default=False)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True)

scenicarea/apps/conversation/models.py
from django.db import models
from django.contrib.auth.models import User


from apps.merchant.models import Commodity


# Create your models here.
class Conversation(models.Model):
    commodity = models.ForeignKey(Commodity, related_name='conversations', on_delete=models.CASCADE, verbose_name='商品')
    members = models.ManyToManyField(User, related_name='conversations', verbose_name='用户')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    update_date = models.DateTimeField(auto_now=True, verbose_name='更新时间')

    class Meta:
        ordering = ('-update_date',)

class ConversationMessage(models.Model):
    conversation = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE, verbose_name='对话')
    content = models.TextField(verbose_name='消息')
    create_date = models.DateTimeField(auto_now_add=True, verbose_name='创建时间')
    created_by = models.ForeignKey(User, related_name='created_messages', on_delete=models.CASCADE, verbose_name='发起用户')

scenicarea/apps/merchant/models.py
from django.db import models
from django.contrib.auth.models import User

from datetime import date, datetime

# Create your models here.
class Commodity(models.Model):
    title = models.CharField(verbose_name='标题', max_length=200)
    details = models.TextField(verbose_name='商品详情', max_length=2000)
    price = models.DecimalField(verbose_name='商品价格', max_digits=5, decimal_places=2)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, blank=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True, blank=True)
    inventory = models.PositiveIntegerField(verbose_name='商品库存', blank=True, default=0)
    picture = models.ImageField(verbose_name='商品主图', upload_to='images/')
    user = models.ForeignKey(User, related_name='commodity', on_delete=models.CASCADE, default=1)


    def __str__(self) -> str:
        return self.title
    
class AssistantImages(models.Model):
    picture = models.ImageField(verbose_name='商品主图', upload_to='images/', null=True, blank=True, default=None)
    commodity = models.ForeignKey(Commodity, on_delete=models.CASCADE)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True, blank=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True, blank=True)

scenicarea/apps/api/forms.py
from django import forms

from .models import Concern, GiftRelationship

TEXTINPUTCLASS = 'form-control'

class ConcernForm(forms.ModelForm):
    class Meta:
        model = Concern
        fields = ('passive_by',)
        widgets = {
            'passive_by': forms.TextInput(attrs={'class': TEXTINPUTCLASS, 'type': 'hidden'}),
        }

class GiftRelationshipForm(forms.ModelForm):
    class Meta:
        model = GiftRelationship
        fields = ('address', 'receive_user', 'status')
        widgets = {
            'address': forms.TextInput(attrs={'class': TEXTINPUTCLASS}),
            'receive_user': forms.Select(attrs={'class': 'form-select'}),
        }

    # def clean_receive_user(self):
    #     receiveuser = self.cleaned_data.get('receive_user')
    #     if not receiveuser:
    #         raise forms.ValidationError('没有提供有效的接收人')
    #     return receiveuser
    
    # def clean_address(self, *args, **kwargs):
    #     address = self.cleaned_data.get('address')
    #     if 'a' in address:
    #         raise forms.ValidationError('没有提供有效的接收人')
    #     return address

scenicarea/apps/conversation/forms.py
from django import forms

from .models import ConversationMessage


TEXTINPUTCLASS = 'form-control'

class ConversationMessageForm(forms.ModelForm):
    class Meta:
        model = ConversationMessage
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={'class': TEXTINPUTCLASS, 'rows':1}),
        }

scenicarea/apps/api/views.py
from django.shortcuts import render, HttpResponse, redirect, get_object_or_404
from django.urls import reverse
from django.db.models import F, Q
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django import forms

from .forms import ConcernForm, GiftRelationshipForm
from .models import Concern, Nexus, GiftStatus, Gift, GiftRelationship

from apps.merchant.forms import SingupForm
from apps.merchant.models import Commodity

from apps.conversation.models import Conversation, ConversationMessage

from apps.wallet.models import Wallet

# Create your views here.
def index(request):
    queryset_commodity = Commodity.objects.all()
    context = {
        'queryset': queryset_commodity
    }
    return render(request, 'api/index.html', context)

def details(request, id):
    obj_commodity = get_object_or_404(Commodity, id=id)
    context = {
        'obj': obj_commodity
    }
    return render(request, 'api/details.html', context)

def sing_up(request):
    if request.method == 'POST':
        form = SingupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('api:log_in'))
    else:
        form = SingupForm()
    context = {
        'form': form
    }
    return render(request, 'api/sing_up.html', context)

def center(request):
    return render(request, 'api/center.html')

@login_required(login_url='/login/')
def conversation(request):
    conversations = Conversation.objects.select_related('commodity').filter(members__id__in=[request.user.id])
    context = {
        'conversations': conversations
    }
    return render(request, 'api/conversation.html', context)

@login_required(login_url='/login/')
def friend_list(request):
    concern = Concern.objects.filter(created_by=request.user, nexus__id=1)
    context = {
        'concern': concern,
    }
    return render(request, 'api/friend_list.html', context)

@login_required(login_url='/login/')
def search_friend(request):
    user = None
    query = request.GET.get('query')

    if query:
        user = User.objects.filter(username__icontains=query)

    if request.method == 'POST':
        concern = Concern.objects.filter(created_by=request.user, passive_by=request.POST.get('passive_by')).exists()
        if concern:
            return redirect(f'/friend/search/?query={query}')
        form = ConcernForm(request.POST)
        if form.is_valid():
            concern = form.save(commit=False)
            concern.nexus = Nexus.objects.get(id=1)
            concern.created_by = request.user
            concern.save()
            return redirect(f'/friend/search/?query={query}')
    else:
        form = ConcernForm()
    context = {
        'user': user,
        'query': query,
        'form': form,
    }
    return render(request, 'api/friend_search.html', context)

@login_required(login_url='/login/')
def delete_friend(request, id):
    Concern.objects.filter(id=id, created_by=request.user).delete()
    return redirect(reverse('api:friend_list'))

@login_required(login_url='/login/')
def gift_index(request):
    giftrelation = GiftRelationship.objects.filter(gift_user=request.user)
    context = {
        'giftrelation': giftrelation,
    }
    return render(request, 'api/gift.html', context)

@login_required(login_url='/login/')
def gift_receive_index(request):
    giftrelation = GiftRelationship.objects.filter(receive_user=request.user)
    context = {
        'giftrelation': giftrelation,
    }
    return render(request, 'api/gift.html', context)

@login_required(login_url='/login/')
def gift_details(request, id):
    giftrelation = GiftRelationship.objects.filter(Q(gift__id=id), Q(gift_user=request.user) | Q(receive_user=request.user)).last()
    context = {
        'giftrelation': giftrelation,
    }
    return render(request, 'api/gift_details.html', context)

@login_required(login_url='/login/')
def gift_receive(request, id):
    giftrelation = GiftRelationship.objects.filter(
        Q(gift__id=id),     
        Q(receive_user=request.user), 
        Q(status__id=1) | Q(status__id=3)
    ).first()
    giftrelation.status_id = 2
    giftrelation.save()
    return redirect(reverse('api:gift_details', kwargs={'id': id}))

@login_required(login_url='/login/')
def new_gift(request, id):
    concerns = None
    obj = get_object_or_404(Commodity, id=id)
    concerns = Concern.objects.filter(created_by=request.user)
    wallet = get_object_or_404(Wallet, user=request.user)
    if request.method == "POST":
        form = GiftRelationshipForm(request.POST)
        if wallet.balance > obj.price:
            if form.is_valid():
                gift = Gift.objects.create(commodity=obj)
                giftrelation = form.save(commit=False)
                giftrelation.gift = gift
                giftrelation.gift_user = request.user
                giftrelation.save()
                wallet.balance = F('balance') - obj.price
                wallet.save()
                return redirect(reverse('api:gift_index'))
        else:
            form.add_error(None, forms.ValidationError(('您的余额不足'), code=400))
    else:
        form = GiftRelationshipForm()
    context = {
        'obj': obj,
        'concerns': concerns,
        'form': form,
        'url': reverse('api:new_gift', kwargs={'id': obj.id}),
        'status': 1,
    }
    return render(request, 'api/new_gift.html', context)

@login_required(login_url='/login/')
def forward_gift(request, gift_id, good_id):
    concerns = None
    gift = get_object_or_404(Gift, id=gift_id)
    obj = get_object_or_404(Commodity, id=good_id)
    concerns = Concern.objects.filter(created_by=request.user)
    if request.method == "POST":
        form = GiftRelationshipForm(request.POST)
        if form.is_valid():
            GiftRelationship.objects.filter(gift=gift).update(forward=True)
            giftrelation = form.save(commit=False)
            giftrelation.gift = gift
            giftrelation.gift_user = request.user
            giftrelation.save()
            return redirect(reverse('api:gift_index'))
    else:
        form = GiftRelationshipForm()
    context = {
        'obj': obj,
        'concerns': concerns,
        'form': form,
        'url': reverse('api:forward_gift', kwargs={'gift_id': gift.id, 'good_id': obj.id}),
        'status': 3,
    }
    return render(request, 'api/new_gift.html', context)

scenicarea/apps/conversation/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from .models import Conversation
from .forms import ConversationMessageForm

from apps.merchant.models import Commodity

# Create your views here.
@login_required(login_url='/login/')
def new_conversation(request, id):
    # 获取要对话的商品
    obj_commodity = get_object_or_404(Commodity, id=id)
   
    if obj_commodity.user == request.user:
        # 如果创建对话的用户是这个商品的创建者
        # 自动定向到这个创建者的商品列表
        return redirect(reverse('merchant:index'))
    
    # 查找对话表中是否存在和这个商品相关的对话
    # 在过滤相关对话记录中关于创建对话用户的所有对话
    obj_conversation = Conversation.objects.filter(commodity=obj_commodity).filter(members__in=[request.user.id]).first()

    if obj_conversation:
        qs_message = obj_conversation.messages.all()
    else:
        qs_message = []

    if request.method == 'POST':
        # 把发送的信息放到form中验证
        form = ConversationMessageForm(request.POST)
        if form.is_valid():
            # 如果验证通过
            # 创建一条关于这个商品的对话
            # 保存创建对话的用户id和关于这个商品的创建者id
            if not obj_conversation:
                obj_conversation = Conversation.objects.create(commodity=obj_commodity)
                obj_conversation.members.add(request.user)
                obj_conversation.members.add(obj_commodity.user)
                obj_conversation.save()

            # 把发送的信息保存到信息表
            # 在将这条对话的id和创建对话的用户id保存到信息表
            form_conversation_message = form.save(commit=False)
            form_conversation_message.conversation = obj_conversation
            form_conversation_message.created_by = request.user
            form_conversation_message.save()

            # 保存完成重定向到对话页面
            return redirect(reverse('conversation:new', kwargs={'id': id}))
        
    else:
        form = ConversationMessageForm()
    
    context = {
        'form': form,
        'id': id,
        'queryset': qs_message,
    }
    return render(request, 'conversation/new.html', context)

scenicarea/apps/api/templates/api/base.html
{% load static %}

<!doctype html>
<html lang="en-US">
  <head>
    <title>{% block title %}{% endblock %}</title>
    <meta charset="utf-8" />
    <!-- <link rel="stylesheet" type="text/css" href="{% block stylesheet %}{% static "api/css/base.css" %}{% endblock %}"> -->
    <!-- <link rel="stylesheet" href="{% static "admin/css/base.css" %}"> -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.0/font/bootstrap-icons.css">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <style>
      /* 添加自定义样式 */
      body {
          margin-bottom: 70px; /* 为了让按钮不遮挡页面内容 */
      }

      /* 固定按钮的样式 */
      .message {
          position: fixed;
          bottom: 10rem;
          right: 20px;
          z-index: 1000; /* 确保按钮在其他元素之上 */
      }
      .gift {
          position: fixed;
          bottom: 16rem;
          right: 20px;
          z-index: 1000; /* 确保按钮在其他元素之上 */
      }
  </style>
  </head>
  <body>
      <div class="container-fluid" id="container">
        <div id="header" class="sticky-top">
          {% block header %}
          <div class="row" style="background-color: #21A936; color: #ffffff;">
            <div class="col-auto py-3">
              <h3 class="mb-0">欢迎</h3>
            </div>
            <div class="col-auto align-self-center ms-auto gx-0">
              <a href="{% url 'api:index' %}" class="btn">首页</a>
            </div>
            <div class="col-auto align-self-center gx-0">
              <a href="{% url 'api:log_in' %}" class="btn">登录</a>
            </div>
            <div class="col-auto align-self-center gx-0">
              <a href="{% url 'api:sing_up' %}" class="btn">注册</a>
            </div>
          </div>
          {% endblock %}
        </div>
        <div id="main">{% block main %}{% endblock %}</div>
        <div id="footer" class="fixed-bottom">
          {% block footer %}
          <div class="row row-cols-3 text-center py-3 align-items-center border-top border-dark border-opacity-25" style="background-color: #ffffff; color: #21A936;">

            <div class="col px-0">
              <a href="/" style="outline: none; text-decoration: none;" class="link-dark">              
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-shop" viewBox="0 0 16 16">
                <path d="M2.97 1.35A1 1 0 0 1 3.73 1h8.54a1 1 0 0 1 .76.35l2.609 3.044A1.5 1.5 0 0 1 16 5.37v.255a2.375 2.375 0 0 1-4.25 1.458A2.371 2.371 0 0 1 9.875 8 2.37 2.37 0 0 1 8 7.083 2.37 2.37 0 0 1 6.125 8a2.37 2.37 0 0 1-1.875-.917A2.375 2.375 0 0 1 0 5.625V5.37a1.5 1.5 0 0 1 .361-.976l2.61-3.045zm1.78 4.275a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0 1.375 1.375 0 1 0 2.75 0V5.37a.5.5 0 0 0-.12-.325L12.27 2H3.73L1.12 5.045A.5.5 0 0 0 1 5.37v.255a1.375 1.375 0 0 0 2.75 0 .5.5 0 0 1 1 0zM1.5 8.5A.5.5 0 0 1 2 9v6h1v-5a1 1 0 0 1 1-1h3a1 1 0 0 1 1 1v5h6V9a.5.5 0 0 1 1 0v6h.5a.5.5 0 0 1 0 1H.5a.5.5 0 0 1 0-1H1V9a.5.5 0 0 1 .5-.5zM4 15h3v-5H4v5zm5-5a1 1 0 0 1 1-1h2a1 1 0 0 1 1 1v3a1 1 0 0 1-1 1h-2a1 1 0 0 1-1-1v-3zm3 0h-2v3h2v-3z"/>
                </svg>
                <p class="mb-0 fs-6">首页</p>
              </a>
            </div>
      
            <div class="col px-0">
              <a href="{% url 'api:conversation' %}" style="outline: none; text-decoration: none;" class="link-dark"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-square-dots" viewBox="0 0 16 16">
                  <path d="M14 1a1 1 0 0 1 1 1v8a1 1 0 0 1-1 1h-2.5a2 2 0 0 0-1.6.8L8 14.333 6.1 11.8a2 2 0 0 0-1.6-.8H2a1 1 0 0 1-1-1V2a1 1 0 0 1 1-1h12zM2 0a2 2 0 0 0-2 2v8a2 2 0 0 0 2 2h2.5a1 1 0 0 1 .8.4l1.9 2.533a1 1 0 0 0 1.6 0l1.9-2.533a1 1 0 0 1 .8-.4H14a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2z"/>
                  <path d="M5 6a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0zm4 0a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                </svg>
                <p class="mb-0">消息</p>
              </a>
            </div>

            <div class="col px-0">
              <a href="{% url 'api:center' %}" style="outline: none; text-decoration: none;" class="link-dark"> 
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-emoji-heart-eyes" viewBox="0 0 16 16"><path d="M8 15A7 7 0 1 1 8 1a7 7 0 0 1 0 14zm0 1A8 8 0 1 0 8 0a8 8 0 0 0 0 16z"/><path d="M11.315 10.014a.5.5 0 0 1 .548.736A4.498 4.498 0 0 1 7.965 13a4.498 4.498 0 0 1-3.898-2.25.5.5 0 0 1 .548-.736h.005l.017.005.067.015.252.055c.215.046.515.108.857.169.693.124 1.522.242 2.152.242.63 0 1.46-.118 2.152-.242a26.58 26.58 0 0 0 1.109-.224l.067-.015.017-.004.005-.002zM4.756 4.566c.763-1.424 4.02-.12.952 3.434-4.496-1.596-2.35-4.298-.952-3.434zm6.488 0c1.398-.864 3.544 1.838-.952 3.434-3.067-3.554.19-4.858.952-3.434z"/></svg>
                <p class="mb-0">我的</p>
              </a>
            </div>
            
          </div>
          {% endblock %}
        </div>
      </div>
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-ep+dxp/oz2RKF89ALMPGc7Z89QFa32C8Uv1A3TcEK8sMzXVysblLA3+eJWTzPJzT" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.bundle.min.js" integrity="sha384-/mhDoLbDldZc3qpsJHpLogda//BVZbgYuw6kof4u2FrCedxOtgRZDTHgHUhOCVim" crossorigin="anonymous"></script>  
  </body>
</html>

scenicarea/apps/api/templates/api/center.html
{% extends 'api/index.html' %}
{% load static %}

{% block title %}用户中心{% endblock %}

{% block header %}
<div class="row" style="background-color: #21A936; color: #ffffff;">
  <div class="col-12 py-3 text-center">
    <h3 class="mb-0">{% block h_title %}用户中心{% endblock %}</h3>
  </div>
</div>


{% block search %}

{% endblock %}

{% endblock %}

{% block main %}
<div class="row align-items-center" style="background-color: #f58668; height: 10rem; color: #ffffff;">
    <div class="col-auto pe-0">
        <p class="mb-0 fs-1 ">
            {% if request.user.is_authenticated %}{{request.user}}{% else %}<a href="{% url 'api:log_in' %}" style="outline: none; text-decoration: none;" class="link-dark">立即登录</a>{% endif %}
        </p>
    </div>
    {% if request.user.is_authenticated %}
        <div class="col-auto">
            <p class="mb-0">
                V1
            </p>
        </div>
    {% endif %}
    {% if request.user.is_authenticated %}
    <div class="col-auto ms-auto">
        <a href="{% url 'api:log_out' %}" style="outline: none; text-decoration: none;" class="link-light btn btn-primary">
            退出登录
        </a>
    </div>
    {% endif %}
</div>
{% if request.user.is_authenticated %}
    <a href="{% url 'api:friend_list' %}" style="outline: none; text-decoration: none;" class="link-dark">
        <div class="row align-items-center" style="background-color: #ffffff; height: 4rem;">
            <div class="col-auto">
                <p class="mb-0">
                    好友列表
                </p>
            </div>
        </div>
    </a>
    <div class="row align-items-center">
        <div class="col-12">
            <hr class="my-0">
        </div>
    </div>
    <a href="{% url 'api:gift_index' %}" style="outline: none; text-decoration: none;" class="link-dark">
        <div class="row align-items-center" style="background-color: #ffffff; height: 4rem;">
            <div class="col-auto">
                <p class="mb-0">
                    礼物
                </p>
            </div>
        </div>
    </a>
    <div class="row align-items-center">
        <div class="col-12">
            <hr class="my-0">
        </div>
    </div>
    <a href="{% url 'wallet:index' %}" style="outline: none; text-decoration: none;" class="link-dark">
        <div class="row align-items-center" style="background-color: #ffffff; height: 4rem;">
            <div class="col-auto">
                <p class="mb-0">
                    钱包
                </p>
            </div>
        </div>
    </a>
    <div class="row align-items-center">
        <div class="col-12">
            <hr class="my-0">
        </div>
    </div>
{% endif %}


{% endblock %}

scenicarea/apps/api/templates/api/label.html
{% extends 'api/search.html' %}


{% block table %}
    <div style="display: grid; grid-template-columns: 1fr 1fr 1fr; text-align: center; font-size: 24px;">
        <div>积分抢购</div>
        <div>积分精选</div>
        <div>积分折扣</div>
    </div>
{% endblock %}

{% block goods %}
{% endblock %}

scenicarea/apps/api/templates/api/search.html
{% extends 'api/base.html' %}

{% block search %}
    <div style="text-align: center; font-size: 26px; color: #aeaeae;">搜索</div>
{% endblock %}

{% block table %}
{% endblock %}