scenicarea/apps/wallet/urls.py
from django.urls import path, reverse

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<int:id>/recharge/', views.recharge, name='recharge'),
]
app_name = 'wallet'

scenicarea/scenicarea/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.api.urls')),
    path('merchant/', include('apps.merchant.urls')),
    path('inbox/', include('apps.conversation.urls')),
    path('wallet/', include('apps.wallet.urls'),)
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

scenicarea/apps/wallet/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Wallet(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True)
    balance = models.DecimalField(verbose_name='余额', max_digits=9, decimal_places=2, default=0.00)
    create_date = models.DateTimeField(verbose_name='创建时间', auto_now_add=True)
    update_date = models.DateTimeField(verbose_name='更新时间', auto_now=True)

scenicarea/apps/wallet/forms.py
from django import forms

from .models import Wallet

TEXTINPUTCLASS = 'form-control form-control-lg'

class WalletForm(forms.ModelForm):
    class Meta:
        model = Wallet
        fields = ('balance',)
        widgets = {
            'balance': forms.NumberInput(attrs={'class': TEXTINPUTCLASS, 'placeholder':'输入你的充值金额'})
        }

    def clean_balance(self):
        balance = self.cleaned_data.get('balance')
        print(balance)
        if balance <= 0:
            raise forms.ValidationError('充值金额不能小于0')
        else:
            return balance

scenicarea/apps/wallet/views.py
from django.shortcuts import render,HttpResponse, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.db.models import F

from .models import Wallet
from .forms import WalletForm

# Create your views here.
@login_required
def index(request):
    wallet = Wallet.objects.filter(user=request.user).exists()
    if wallet:
        wallet = Wallet.objects.get(user=request.user)
    else:
        wallet = Wallet.objects.create(user=request.user)
    context = {
        'wallet': wallet,
    }
    return render(request, 'wallet/index.html', context)

@login_required
def recharge(request, id):
    print(request.POST)
    wallet = get_object_or_404(Wallet, user=request.user, user__id=id)
    if request.method == 'POST':
        form = WalletForm(request.POST, instance=wallet)
        if form.is_valid():
            wallet.balance = F('balance') + form.cleaned_data.get('balance')
            wallet.save()
            return redirect(reverse('wallet:index'))
    else:
        form = WalletForm()
    context = {
        'wallet': wallet,
        'form': form,
    }
    return render(request, 'wallet/recharge.html', context)

scenicarea/apps/wallet/templates/wallet/index.html
{% extends 'api/index.html' %}
{% load static %}

{% block title %}钱包{% endblock %}

{% block header %}
<div class="row" style="background-color: #21A936; color: #ffffff;">
  <div class="col-12 py-3 text-center">
    <h3 class="mb-0">{% block h_title %}钱包{% endblock %}</h3>
  </div>
</div>


{% block search %}

{% endblock %}

{% endblock %}

{% block main %}
<div class="row text-center py-4">
    <div class="col-12">
        <div class="row mb-3">
            <div class="col-12">
                <h3 class="mb-0">目前余额</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h3 class="mb-0" style="font-size: 4.5rem;"><small style="font-size: 2.5rem;">￥</small>{{wallet.balance}}</h3>
            </div>
        </div>
        <div class="row py-5">
            <div class="col-12">
                <a href="{% url 'wallet:recharge' wallet.user.id %}" class="btn btn-primary" style="--bs-btn-padding-x: 9rem; --bs-btn-padding-y: 1rem;">充值</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

scenicarea/apps/wallet/templates/wallet/recharge.html
{% extends 'api/index.html' %}
{% load static %}

{% block title %}余额充值{% endblock %}

{% block header %}
<div class="row" style="background-color: #21A936; color: #ffffff;">
  <div class="col-12 py-3 text-center">
    <h3 class="mb-0">{% block h_title %}余额充值{% endblock %}</h3>
  </div>
</div>


{% block search %}

{% endblock %}

{% endblock %}

{% block main %}
<div class="row text-center py-4">
    <div class="col-12">
        <div class="row mb-3">
            <div class="col-12">
                <h3 class="mb-0">目前余额</h3>
            </div>
        </div>
        <div class="row">
            <div class="col-12">
                <h3 class="mb-0" style="font-size: 4.5rem;"><small style="font-size: 2.5rem;">￥</small>{{wallet.balance}}</h3>
            </div>
        </div>
        <div class="row py-5">
            <div class="col-12">
                <form action="." method="post">
                    {% csrf_token %}
                    {{form.balance}}
                    {% if form.errors or form.non_field.errors %}
                    <div class="row mt-1">
                        <div class="col-auto">
                            {{form.balance.errors}}
                        </div>
                    </div>
                    {% endif %}
                    <button type="submit" class="btn btn-primary mt-5" style="--bs-btn-padding-x: 9rem; --bs-btn-padding-y: 1rem;">充值</button>

                </form>
            </div>
        </div>
    </div>
</div>


{% endblock %}